# Generated by Django 5.2 on 2025-04-17 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticket',
            old_name='ticket',
            new_name='description',
        ),
        migrations.AddField(
            model_name='ticket',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
